language: bash
before_install:
- openssl aes-256-cbc -K $encrypted_04645295b67a_key -iv $encrypted_04645295b67a_iv
  -in cert.pem.enc -out cert.pem -d
script:
- export packer_host=$(curl -X GET "http://ec2-52-17-22-205.eu-west-1.compute.amazonaws.com:5000/")
- echo $packer_host
- chmod 600 cert.pem
- rsync -a -arvce "ssh -i cert.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  . packer@$packer_host:/tmp/${TRAVIS_BUILD_ID}
- ssh -t -t -i cert.pem -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  packer@$packer_host "${TRAVIS_BUILD_ID}"
after_success:
- echo "ok"